name: "Your_PR_name"

on:
  push:
    branches:
      - your_branch





############################################################################################
########### DO NOT CHANGE THIE #############################################################
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.6.*
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.*

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Cache pipenv virtualenv
        id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/Python/
          key: ${{ runner.os }}-venv-mlmodels-${{ hashFiles('**/install/requirements_fake.txt') }}

      - name: Install numpy
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pip install numpy

      - name: Install repo requirements  1
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pip install -r install/requirements.txt

      - name: Install repo requirements   2
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pip install -r install/requirements_fake.txt

      - name: Install repo
        run: pip install -e . -r install/requirements.txt   --no-deps

      - name: repo path
        run: python -c "import mlmodels,os ; print(mlmodels); print(os)"

######################################################################################
######################################################################################




      ########  Test running   #######################################################
      ##### Please change BELOW to your file names  ##################################
      - name: test_myfiles
        run:  |
            python mlmodels/model_tch/matchzoo_models.py 
            python pullrequest/mytest_pr.py 




