name: docs_github_pages arita37.github.io/myutil/en/yushao/
 
# execute this workflow automatically when a we push to main
on:
  push:
    branches:
      - main
      - yushao

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v1
    #  ref: ${{ github.head_ref }
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
    - name: Set up Python 3.7.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.*
      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      
  
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**py36.txt') }}
          

    #- name: Install numpy
    #  if: steps.cache-pipenv.outputs.cache-hit != 'true'
    #  run: pip install numpy==1.18.2   pillow==6.2.1  scipy
      

    - name: Install repo requirements  1
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
           pip install -r  py36_min.txt


    - name: Install utilmy
      run:  |
        pip install -e .
        python -c "import utilmy"

           
    - name: Install repo requirements   2
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        ls .
        pip install -r  py36.txt
        #pip install -r install/requirements_fake.txt


    - name: test_import
      run: |
           python -c "import os, pandas as pd; print(os)"
           python -c "import utilmy"        
        
        
    ################################################################################
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #run: |
      #  apt-get update
      #  apt-get install -y git

    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chmod -R 777 docs_ghpage
        docs_ghpage/buildDocs.sh
      shell: bash


